# ----------------------------------------------------------------------------
#
# Package             : cloud-sdk-docker
# Source Repo         : https://github.com/GoogleCloudPlatform/cloud-sdk-docker.git
# Travis Job Link     : https://travis-ci.com/github/asellappen/cloud-sdk-docker/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: generic

dist: focal

arch:
 - amd64
 - ppc64le
 
services:
  - docker
  
scripts: 
  - docker pull gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  - docker run gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  - Google Cloud SDK 159.0.0
